name: Docs deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    permissions:
      pages: write      # to deploy to Pages
      id-token: write  # to authenticate with Cloudflare
    steps:
      - uses: actions/checkout@v4

      - name: build docs
        run: |
          yarn && yarn build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: .vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # with:
        #   branch: gh-pages
          # folder: docs/.vitepress/dist